const CAT = {
  AK: 'alkali', AE: 'alkaline', LA: 'lanthanide', AC: 'actinide',
  TM: 'transition', PT: 'post-transition', ML: 'metalloid',
  NM: 'nonmetal', HA: 'halogen', NG: 'noble', UK: 'unknown'
};

const catColors = {
  alkali: '#ff4757', alkaline: '#ff6348', lanthanide: '#eccc68', actinide: '#ffa502',
  transition: '#2ed573', 'post-transition': '#1e90ff', metalloid: '#a29bfe',
  nonmetal: '#fd79a8', halogen: '#e17055', noble: '#00cec9', unknown: '#636e72'
};

// [atomic#, symbol, name, mass, category, col, row, history, uses]
const elements = [
  [1,'H','Hydrogen',1.008,CAT.NM,1,1,'Hydrogen was first produced artificially by Henry Cavendish in 1766, who called it "inflammable air." Antoine Lavoisier later named it hydrogen in 1783, from Greek meaning "water-former."','Used in fuel cells, petroleum refining, ammonia production for fertilizers, rocket fuel, and as a clean energy carrier for the future.'],
  [2,'He','Helium',4.003,CAT.NG,18,1,'Helium was first detected in the solar spectrum in 1868 by Pierre Janssen during a solar eclipse. Its name comes from Helios, the Greek god of the Sun. It wasn\'t isolated on Earth until 1895 by William Ramsay.','Used in balloons and airships, MRI cooling, arc welding, leak detection, and as a cryogenic coolant for superconducting magnets.'],
  [3,'Li','Lithium',6.941,CAT.AK,1,2,'Lithium was discovered in 1817 by Johan August Arfwedson while analyzing petalite ore. Its name derives from the Greek "lithos" meaning stone. It was the third element discovered in the 19th century.','Powers rechargeable batteries in phones and EVs, used in mood-stabilizing medications, nuclear fusion research, glass ceramics, and lubricating greases.'],
  [4,'Be','Beryllium',9.012,CAT.AE,2,2,'Beryllium was discovered in 1798 by Louis-Nicolas Vauquelin in beryl and emerald minerals. It was independently isolated in 1828 by Friedrich Wöhler and Antoine Bussy. Named after the mineral beryl.','Used in aerospace structures, X-ray windows, nuclear reactors as a neutron reflector, high-performance audio speakers, and precision instruments.'],
  [5,'B','Boron',10.811,CAT.ML,13,2,'Boron was first isolated in 1808 by Humphry Davy, Joseph-Louis Gay-Lussac, and Louis-Jacques Thénard. Named after borax, from which it was extracted. It\'s the only metalloid in group 13.','Used in borosilicate glass (Pyrex), fiberglass insulation, high-strength composites, nuclear reactor control rods, and borax detergents and cleaning products.'],
  [6,'C','Carbon',12.011,CAT.NM,14,2,'Carbon has been known since antiquity in the forms of charcoal and soot. Antoine Lavoisier proved it was an element in 1789. Diamond and graphite were identified as carbon forms in the 18th century. The name comes from Latin "carbo" meaning coal.','The basis of all organic life; used in steel production, pencil graphite, carbon fiber composites, diamond tools, activated carbon filters, and emerging graphene electronics.'],
  [7,'N','Nitrogen',14.007,CAT.NM,15,2,'Nitrogen was discovered in 1772 by Daniel Rutherford, who called it "noxious air." Lavoisier named it azote (lifeless) but the name nitrogen (nitro-forming) prevailed. It makes up 78% of Earth\'s atmosphere.','Used in fertilizers (Haber-Bosch process), liquid nitrogen refrigerant, food preservation, electronics manufacturing, and as an inert atmosphere for sensitive processes.'],
  [8,'O','Oxygen',15.999,CAT.NM,16,2,'Oxygen was discovered independently by Carl Wilhelm Scheele in 1772 and Joseph Priestley in 1774. Lavoisier recognized it as an element and named it from Greek meaning "acid-former." It\'s essential for respiration.','Essential for all aerobic life; used in medical oxygen therapy, steel and metal smelting, rocket propellant, water treatment, and chemical manufacturing.'],
  [9,'F','Fluorine',18.998,CAT.HA,17,2,'Fluorine\'s existence was predicted from hydrofluoric acid studies, but isolating it was so dangerous it killed or injured several chemists. Henri Moissan finally succeeded in 1886 using electrolysis, earning the Nobel Prize.','Used in toothpaste and water fluoridation, Teflon non-stick coatings, refrigerants (Freon), uranium enrichment, and production of semiconductors.'],
  [10,'Ne','Neon',20.180,CAT.NG,18,2,'Neon was discovered in 1898 by William Ramsay and Morris Travers through fractional distillation of liquid air. Its name comes from the Greek "neos" meaning new. It was the second noble gas to be discovered.','Famous for neon signs and lighting, used in high-voltage indicators, TV tubes, wave meter tubes, helium-neon lasers, and cryogenic refrigerants.'],
  [11,'Na','Sodium',22.990,CAT.AK,1,3,'Sodium was first isolated in 1807 by Humphry Davy using electrolysis of molten sodium hydroxide. Its name comes from the English "soda," while its symbol Na is from the Latin "natrium."','Essential electrolyte in biology; used in table salt, baking soda, soap manufacturing, street lamps (sodium vapor), and nuclear reactor coolant.'],
  [12,'Mg','Magnesium',24.305,CAT.AE,2,3,'Magnesium was recognized as an element by Joseph Black in 1755, but only isolated in 1808 by Humphry Davy. Named after Magnesia, a district in Thessaly, Greece. It burns with a brilliant white flame.','Used in lightweight alloys for aerospace and cars, fireworks and flares, dietary supplements, antacids, and as a refractory material in furnaces.'],
  [13,'Al','Aluminium',26.982,CAT.PT,13,3,'Aluminium was predicted by Antoine Lavoisier and first isolated in 1825 by Hans Christian Ørsted. Once rarer than gold, its price plummeted after Charles Hall and Paul Héroult independently developed electrolytic production in 1886.','The most abundant metal in Earth\'s crust; used in aircraft and packaging foil, building construction, beverage cans, electrical wiring, and kitchen cookware.'],
  [14,'Si','Silicon',28.086,CAT.ML,14,3,'Silicon was first isolated in 1823 by Jöns Jacob Berzelius. Named after the Latin "silex" for flint. Though abundant in Earth\'s crust as silica (sand), pure silicon was difficult to obtain until modern methods.','The foundation of modern electronics; used in computer chips and solar cells, glass and ceramics, silicone sealants, fiber optics, and semiconductor devices.'],
  [15,'P','Phosphorus',30.974,CAT.NM,15,3,'Phosphorus was discovered in 1669 by Hennig Brand, who isolated it from urine while searching for the philosopher\'s stone. It glows in the dark due to oxidation — making it the first chemiluminescent substance studied.','Essential in DNA and cell membranes; used in fertilizers (critical for agriculture), detergents, matches and fireworks, flame retardants, and steel production.'],
  [16,'S','Sulfur',32.06,CAT.NM,16,3,'Sulfur has been known since ancient times, mentioned in the Bible as "brimstone." Lavoisier established it as an element in 1789. Volcanic regions provided early supplies; today it\'s largely recovered from petroleum refining.','Used in sulfuric acid production (the world\'s most produced industrial chemical), rubber vulcanization, fertilizers, gunpowder, and fungicides for crops.'],
  [17,'Cl','Chlorine',35.45,CAT.HA,17,3,'Chlorine was discovered in 1774 by Carl Wilhelm Scheele and recognized as an element in 1808 by Humphry Davy. Its name comes from the Greek "chloros" meaning pale green. It was used as a poison gas in WWI.','Used in water purification and disinfection, PVC plastic production, bleaching paper and textiles, pharmaceuticals, and chemical manufacturing.'],
  [18,'Ar','Argon',39.948,CAT.NG,18,3,'Argon was discovered in 1894 by Lord Rayleigh and William Ramsay by removing nitrogen and oxygen from air. Its name comes from the Greek "argos" meaning inactive, reflecting its unreactive nature.','Used in welding as a shielding gas, filling incandescent and fluorescent light bulbs, preserving historical documents, and as an insulating gas in double-pane windows.'],
  [19,'K','Potassium',39.098,CAT.AK,1,4,'Potassium was first isolated in 1807 by Humphry Davy using electrolysis, the first metal isolated this way. Its symbol K comes from the Latin "kalium." It was named from English "potash" (plant ash soaked in water).','Essential nutrient for plant and human health; used in fertilizers, soaps and detergents, food preservation (potassium nitrate), and gunpowder production.'],
  [20,'Ca','Calcium',40.078,CAT.AE,2,4,'Calcium compounds have been used since antiquity (limestone, chalk), but the element was first isolated in 1808 by Humphry Davy via electrolysis. Its name comes from the Latin "calx" meaning lime.','Most abundant mineral in the human body; used in cement and concrete, steel refining, paper production, antacids and supplements, and water treatment.'],
  [21,'Sc','Scandium',44.956,CAT.TM,3,4,'Scandium was predicted by Dmitri Mendeleev in 1871 and discovered in 1879 by Lars Fredrik Nilson in the minerals euxenite and gadolinite. Named after Scandinavia, confirming Mendeleev\'s predictions.','Used in aluminum-scandium alloys for aerospace and sports equipment, high-intensity metal halide lamps, and solid oxide fuel cells.'],
  [22,'Ti','Titanium',47.867,CAT.TM,4,4,'Titanium was discovered in 1791 by William Gregor and independently by Martin Heinrich Klaproth in 1795, who named it after the Titans of Greek mythology. Pure titanium wasn\'t produced until 1910.','Used in aerospace alloys, medical implants and prosthetics, bicycle frames, white paint pigment (TiO₂), and architectural cladding for its strength and corrosion resistance.'],
  [23,'V','Vanadium',50.942,CAT.TM,5,4,'Vanadium was discovered in 1801 by Andrés Manuel del Río but he was convinced his discovery was chromium. It was rediscovered in 1830 by Nils Gabriel Sefström and named after Vanadís (Norse goddess Freya).','Used in high-strength steel alloys for tools and springs, vanadium flow batteries for grid energy storage, titanium alloys for jet engines, and catalysts for sulfuric acid.'],
  [24,'Cr','Chromium',51.996,CAT.TM,6,4,'Chromium was discovered in 1797 by Louis-Nicolas Vauquelin in the mineral crocoite. Named from the Greek "chroma" meaning color, due to the vivid colors of its compounds. It gives rubies their red color.','Used in stainless steel production, chrome plating for corrosion resistance and appearance, pigments (chrome green, yellow), tanning leather, and catalysts.'],
  [25,'Mn','Manganese',54.938,CAT.TM,7,4,'Manganese was isolated in 1774 by Johan Gottlieb Gahn, though its ores had been used in glass-making since ancient times. Named after Magnesia, a region of Greece. It\'s related to the word "magnet."','Essential for steel production (removes sulfur and oxygen), dry cell batteries (MnO₂), aluminum alloy strengthening, fertilizers, and water purification.'],
  [26,'Fe','Iron',55.845,CAT.TM,8,4,'Iron has been worked since at least 3000 BCE, defining the "Iron Age." The Egyptians called it "metal from heaven" (likely from meteorites). Its symbol Fe comes from the Latin "ferrum."','The backbone of industrial civilization; used in steel for construction, vehicles, and machinery; cast iron cookware; magnets; and hemoglobin for oxygen transport in blood.'],
  [27,'Co','Cobalt',58.933,CAT.TM,9,4,'Cobalt was discovered in 1735 by Georg Brandt, who showed it was distinct from bismuth. Named after "kobold," German for goblin, because miners blamed troublesome cobalt ores for making copper smelting fail.','Used in lithium-ion battery cathodes (phones, EVs), blue pigments for glass and ceramics, magnetic alloys, jet engine superalloys, and cancer radiation therapy (Co-60).'],
  [28,'Ni','Nickel',58.693,CAT.TM,10,4,'Nickel was discovered in 1751 by Axel Fredrik Cronstedt. Its name comes from the German "Kupfernickel" (devil\'s copper) because miners couldn\'t extract copper from nickel-bearing ore despite its copper-like appearance.','Used in stainless steel and superalloys, rechargeable batteries (NiMH, nickel-cadmium), coinage, electroplating, and catalysts for hydrogenation reactions.'],
  [29,'Cu','Copper',63.546,CAT.TM,11,4,'One of the first metals worked by humans (~9000 BCE), copper gave name to the Chalcolithic (Copper Age). The Romans got much of theirs from Cyprus, giving copper its symbol Cu from "cuprum."','Essential for electrical wiring (highest conductivity of non-precious metals), plumbing, coins, antimicrobial surfaces, bronze and brass alloys, and electric motors.'],
  [30,'Zn','Zinc',65.38,CAT.TM,12,4,'Zinc was officially discovered in 1746 by Andreas Sigismund Marggraf, though zinc alloys (brass) were made in ancient times. India produced zinc metal centuries before Europe. Its name likely comes from German "Zinke" meaning prong.','Used in galvanizing steel to prevent rust, die-casting for auto parts, brass alloys, sunscreen (zinc oxide), dietary supplements, and anti-corrosion paints.'],
  [31,'Ga','Gallium',69.723,CAT.PT,13,4,'Gallium was predicted by Mendeleev as "eka-aluminum" and discovered in 1875 by Paul-Émile Lecoq de Boisbaudran via spectroscopy. It melts in the palm of your hand (30°C) and was one of the first confirmations of Mendeleev\'s predictions.','Used in semiconductors (GaAs, GaN) for LEDs, laser diodes, solar cells, and 5G transistors; thermometers replacing mercury; and as a gallium-indium alloy in nuclear reactors.'],
  [32,'Ge','Germanium',72.630,CAT.ML,14,4,'Germanium was predicted by Mendeleev as "eka-silicon" and discovered in 1886 by Clemens Winkler, perfectly matching the prediction. This discovery was a major triumph for the periodic table.','Used in fiber optic cables (infrared windows), semiconductor devices, night-vision equipment, solar cells, and as a catalyst in PET plastic production.'],
  [33,'As','Arsenic',74.922,CAT.ML,15,4,'Arsenic has been known since ancient times and was used as a poison in medieval Europe (called "inheritance powder"). Albertus Magnus is credited with isolating it in 1250. Its name comes from Greek for yellow orpiment.','Used in wood preservation (CCA), semiconductor compounds (GaAs), pesticides, lead-acid batteries, and historically in medicines and pigments (now largely discontinued).'],
  [34,'Se','Selenium',78.971,CAT.NM,16,4,'Selenium was discovered in 1817 by Jöns Jacob Berzelius as a byproduct of sulfuric acid production. Named after the Moon goddess Selene, because it accompanies tellurium (Earth). It\'s a photoconductor.','Used in glass manufacturing (decolorizing), photovoltaic solar cells, photocopier drums, dietary supplements, rubber production, and semiconductors.'],
  [35,'Br','Bromine',79.904,CAT.HA,17,4,'Bromine was discovered in 1826 by Antoine Jérôme Balard and independently by Carl Jacob Löwig. Named from Greek "bromos" meaning stench, due to its pungent smell. It\'s one of only two liquid elements at room temperature.','Used in flame retardants, water purification for pools, pharmaceutical intermediates, fumigants for soil treatment, and photographic films.'],
  [36,'Kr','Krypton',83.798,CAT.NG,18,4,'Krypton was discovered in 1898 by William Ramsay and Morris Travers by evaporating liquid argon residue. Named from Greek "kryptos" meaning hidden. From 1960–1983, the meter was officially defined by krypton-86 emission.','Used in fluorescent lights and photography flashes, krypton-fluoride excimer lasers for semiconductor lithography, mixed with argon in energy-saving windows.'],
  [37,'Rb','Rubidium',85.468,CAT.AK,1,5,'Rubidium was discovered in 1861 by Robert Bunsen and Gustav Kirchhoff using spectroscopy — one of the first elements discovered this way. Named for its deep red spectral lines ("rubidus" in Latin).','Used in atomic clocks (rubidium frequency standards), GPS systems, research applications, and fireworks for purple-red color; limited commercial applications.'],
  [38,'Sr','Strontium',87.62,CAT.AE,2,5,'Strontium was discovered in 1787 in the mineral strontianite, found near Strontian, Scotland. Independently isolated by Humphry Davy in 1808. Its radioactive isotope Sr-90 is a serious nuclear fallout product.','Used in fireworks and flares for brilliant red color, cathode ray tube glass (now declining), ferrite ceramic magnets, and Sr-90 in nuclear batteries.'],
  [39,'Y','Yttrium',88.906,CAT.TM,3,5,'Yttrium was discovered in 1794 by Johan Gadolin in the mineral ytterbite from Ytterby, Sweden — a quarry that gave names to four elements. Named after this small Swedish village.','Used in phosphors for TV screens and LED lighting, yttrium-aluminum garnet (YAG) lasers, superconductors (YBCO), cancer treatments, and strengthening alloys.'],
  [40,'Zr','Zirconium',91.224,CAT.TM,4,5,'Zirconium was discovered in 1789 by Martin Heinrich Klaproth in the mineral zircon. Isolated in pure form only in 1914. Zircons are among the oldest known minerals (4.4 billion years) and are used for radiometric dating.','Used as nuclear reactor fuel cladding (transparent to neutrons), cubic zirconia gemstones, refractory ceramics, dental ceramics, and corrosion-resistant alloys.'],
  [41,'Nb','Niobium',92.906,CAT.TM,5,5,'Niobium was discovered in 1801 by Charles Hatchett in a mineral from Connecticut. Named after Niobe, daughter of Tantalus (due to its similarity to tantalum). For a century it was called columbium in the USA.','Used in high-strength low-alloy steels for pipelines and cars, superconducting magnets for MRI and particle accelerators, jet engine superalloys, and superconducting qubits.'],
  [42,'Mo','Molybdenum',95.96,CAT.TM,6,5,'Molybdenum was discovered as a distinct element in 1778 by Carl Wilhelm Scheele. Its name comes from the Greek "molybdos" meaning lead, as its ores were confused with lead ores. Isolated in 1781 by Peter Jacob Hjelm.','Used in high-strength steel alloys (tool steels, stainless steel), lubricants (MoS₂), catalysts in petroleum refining, and is an essential trace element in all living organisms.'],
  [43,'Tc','Technetium',98,CAT.TM,7,5,'Technetium was the first artificially produced element, predicted by Mendeleev as "eka-manganese." It was created in 1937 by Carlo Perrier and Emilio Segrè by bombarding molybdenum with deuterons. Named from Greek "technetos" (artificial).','Tc-99m is the most widely used medical radioisotope in diagnostic imaging (nuclear medicine scans), particularly for cancer detection, bone scans, and heart imaging.'],
  [44,'Ru','Ruthenium',101.07,CAT.TM,8,5,'Ruthenium was discovered in 1844 by Karl Ernst Claus in platinum ore residues. Named after Ruthenia, the Latin name for Russia. It was the last naturally occurring platinum group metal to be discovered.','Used as a hardening agent in platinum and palladium alloys, in electrical contacts, solar energy cells, catalysts for hydrogen production, and as an ink in fountain pens.'],
  [45,'Rh','Rhodium',102.906,CAT.TM,9,5,'Rhodium was discovered in 1803 by William Hyde Wollaston in crude platinum ore. Named after the Greek "rhodon" (rose) due to the rose color of rhodium chloride solutions. It is one of the rarest elements on Earth.','Used primarily in catalytic converters for cars (three-way catalysts), electroplating for jewelry and optics, and as a catalyst in chemical reactions.'],
  [46,'Pd','Palladium',106.42,CAT.TM,10,5,'Palladium was discovered in 1803 by William Hyde Wollaston, who named it after the asteroid Pallas, discovered two years earlier. It was controversially published anonymously. One of the platinum group metals.','Used in catalytic converters (alongside rhodium and platinum), hydrogen storage and purification, jewelry (white gold alloys), electronics, and dentistry.'],
  [47,'Ag','Silver',107.868,CAT.TM,11,5,'Silver has been known and worked since at least 3000 BCE. Its symbol Ag comes from the Latin "argentum." Ancient civilizations in Anatolia and Greece mined silver extensively. It has the highest electrical and thermal conductivity of all metals.','Used in jewelry and silverware, photographic film (historically), electrical contacts, solar panels, antimicrobial applications in medicine, and mirrors.'],
  [48,'Cd','Cadmium',112.411,CAT.TM,12,5,'Cadmium was discovered in 1817 by Friedrich Strohmeyer as an impurity in zinc carbonate. Named after "cadmia" (calamine, a zinc ore) or Cadmus, the mythological Phoenician prince. It often accompanies zinc ores.','Used in rechargeable nickel-cadmium batteries, yellow/orange pigments, electroplating for corrosion resistance, neutron absorbers in nuclear reactors (though now restricted due to toxicity).'],
  [49,'In','Indium',114.818,CAT.PT,13,5,'Indium was discovered in 1863 by Ferdinand Reich and Hieronymous Theodor Richter via spectroscopy, identified by its indigo blue spectral line. Named after this characteristic color. It\'s a soft, silver-white metal.','Used in indium tin oxide (ITO) transparent conductors for LCD screens and touchscreens, low-melting alloys, bearings, solders, and thin-film solar cells.'],
  [50,'Sn','Tin',118.710,CAT.PT,14,5,'Tin has been used since ancient times, primarily in bronze (tin-copper alloy), which defined the Bronze Age (~3300–1200 BCE). Its symbol Sn comes from the Latin "stannum." Cornwall was a major ancient tin source.','Used in food can coatings (tinplate), solder for electronics, bronze and pewter alloys, window glass manufacturing (float glass process), and organ pipes.'],
  [51,'Sb','Antimony',121.760,CAT.ML,15,5,'Antimony has been known since ancient Egypt, used in eye cosmetics as kohl. Isolated as a pure element in the 17th century. Its symbol Sb comes from "stibium." The alchemist Basil Valentine wrote extensively about it.','Used in flame retardants (most important use), lead-acid battery grids, semiconductor devices, pewter and britannia metal alloys, and historically in type metal for printing.'],
  [52,'Te','Tellurium',127.60,CAT.ML,16,5,'Tellurium was discovered in 1782 by Franz-Joseph Müller von Reichenstein in a Transylvanian gold ore. Named after Earth (Tellus) by Martin Heinrich Klaproth. It is one of the rarest stable elements in Earth\'s crust.','Used in CdTe thin-film solar cells, thermoelectric devices, alloys to improve machinability of steel and copper, rewritable optical discs, and rubber vulcanization.'],
  [53,'I','Iodine',126.904,CAT.HA,17,5,'Iodine was discovered in 1811 by Bernard Courtois while extracting sodium from seaweed ash — he noticed a purple vapor. Named from Greek "ioeides" (violet-colored). It was quickly recognized for medical uses.','Used as an antiseptic, in thyroid medications, iodized salt to prevent goiter, contrast agents in medical imaging, and as a catalyst in polymer synthesis.'],
  [54,'Xe','Xenon',131.293,CAT.NG,18,5,'Xenon was discovered in 1898 by William Ramsay and Morris Travers, the same year as krypton, by fractional distillation of liquid air. Named from Greek "xenos" meaning stranger. It forms compounds despite being noble.','Used in high-intensity discharge lamps (car headlights, cinema projectors), ion propulsion for spacecraft, medical imaging (Xe-133), and as an anesthetic.'],
  [55,'Cs','Caesium',132.905,CAT.AK,1,6,'Caesium was discovered in 1860 by Robert Bunsen and Gustav Kirchhoff using spectroscopy — one of the first elements discovered this way. Named after the Latin "caesius" for sky blue, its spectral color. It\'s the most electropositive stable element.','Caesium-133 defines the SI second (atomic clocks); used in GPS, telecommunications timing, ion propulsion engines, drilling fluids for oil wells, and night-vision equipment.'],
  [56,'Ba','Barium',137.327,CAT.AE,2,6,'Barium was identified in 1774 by Carl Wilhelm Scheele in barite mineral, and isolated in 1808 by Humphry Davy. Named from Greek "barys" meaning heavy, since barite (barium sulfate) is unusually dense.','Used in oil and gas drilling muds (barite), barium sulfate as a contrast agent for GI X-rays, rat poison (barium carbonate), fireworks for green color, and glass manufacturing.'],
  [57,'La','Lanthanum',138.905,CAT.LA,4,9,'Lanthanum was discovered in 1839 by Carl Gustaf Mosander by separating it from cerium nitrate. Named from Greek "lanthanein" meaning to lie hidden, as it was concealed within cerium ore for years.','Used in hydrogen storage alloys for NiMH batteries, camera and telescope lens glass, mischmetal (lighter flint), fluid catalytic cracking of crude oil, and carbon arc lamps.'],
  [58,'Ce','Cerium',140.116,CAT.LA,5,9,'Cerium was discovered in 1803 by Jöns Jacob Berzelius and Wilhelm Hisinger, and independently by Martin Heinrich Klaproth. Named after the asteroid Ceres, discovered two years earlier. It\'s the most abundant rare earth.','Used in catalytic converters, polishing powders for glass and semiconductor wafers, yellow glass pigment, mischmetal for flints, and as a cerium oxide fuel additive.'],
  [59,'Pr','Praseodymium',140.908,CAT.LA,6,9,'Praseodymium was separated from neodymium in 1885 by Carl Auer von Welsbach. Named from Greek "prasios" (leek green) and "didymos" (twin), as it was split from "didymium." Its salts are characteristically green.','Used in high-strength permanent magnets (with neodymium), aircraft engine alloys, yellow glass pigment, and goggles for glassblowers and welders.'],
  [60,'Nd','Neodymium',144.242,CAT.LA,7,9,'Neodymium was separated from praseodymium in 1885 by Carl Auer von Welsbach. Named from Greek for "new twin." The discovery of neodymium-iron-boron magnets in 1982 revolutionized permanent magnet technology.','Creates the strongest permanent magnets (NdFeB), essential for EV motors, wind turbines, headphones, hard drives, MRI machines, and modern electronics.'],
  [61,'Pm','Promethium',145,CAT.LA,8,9,'Promethium was the last of the lanthanides to be discovered, first definitively isolated in 1945 at Oak Ridge National Laboratory from uranium fission products. Named after Prometheus, who stole fire from the gods. It has no stable isotopes.','Used in nuclear-powered batteries for spacecraft and pacemakers, luminous paint (historically), and as a portable X-ray source. All applications are limited due to its radioactivity.'],
  [62,'Sm','Samarium',150.36,CAT.LA,9,9,'Samarium was discovered in 1879 by Paul-Émile Lecoq de Boisbaudran in samarskite mineral, named after Russian mining official Colonel Vasili Samarsky-Bykhovets — making samarium the first element named after a living person.','Used in samarium-cobalt permanent magnets (for high-temperature applications), cancer treatment (Sm-153), and neutron absorbers in nuclear reactors.'],
  [63,'Eu','Europium',151.964,CAT.LA,10,9,'Europium was discovered in 1901 by Eugène-Anatole Demarçay. Named after Europe. Its unusual fluorescence properties were not recognized until decades later, when it became critical for color television technology.','Used in red and blue phosphors for TV and LED screens, euro banknote fluorescent security ink, fluorescent lighting, and as a dopant in lasers.'],
  [64,'Gd','Gadolinium',157.25,CAT.LA,11,9,'Gadolinium was independently discovered in 1880 by Jean Charles Galissard de Marignac and Paul Émile Lecoq de Boisbaudran. Named after Finnish chemist Johan Gadolin, who first studied rare earths in 1794.','Used as MRI contrast agents (gadolinium chelates), neutron absorbers in nuclear reactors, computer memory chips, and in magnetocaloric refrigeration research.'],
  [65,'Tb','Terbium',158.925,CAT.LA,12,9,'Terbium was discovered in 1843 by Carl Gustaf Mosander when he separated it from yttria. Named after Ytterby, Sweden. It was one of four elements named after this single quarry village.','Used in solid-state devices and sensors (terfenol-D magnetostrictive alloy), green phosphors in fluorescent lamps and flat-panel displays, and fuel cells.'],
  [66,'Dy','Dysprosium',162.500,CAT.LA,13,9,'Dysprosium was discovered in 1886 by Paul-Émile Lecoq de Boisbaudran but only isolated in reasonably pure form in the 1950s. Named from Greek "dysprositos" meaning hard to get, reflecting the extreme difficulty of separating it.','Used in neodymium magnets to maintain strength at high temperatures (crucial for EV motors), nuclear reactor control rods, and data storage devices.'],
  [67,'Ho','Holmium',164.930,CAT.LA,14,9,'Holmium was discovered in 1878 by Marc Delafontaine and Jacques-Louis Soret, and independently by Per Teodor Cleve. Named after Holmia, the Latin name for Stockholm, Sweden.','Has the highest magnetic moment of any element; used in nuclear reactor control rods, solid-state lasers for medical procedures, and as a calibration standard for spectrometers.'],
  [68,'Er','Erbium',167.259,CAT.LA,15,9,'Erbium was discovered in 1843 by Carl Gustaf Mosander, along with terbium, from yttria. Named after Ytterby, Sweden. Its pink oxide (erbium oxide) gives a distinctive color to glass.','Used as an amplifier in fiber optic cables (EDFA — erbium-doped fiber amplifiers), pink glass and ceramic colorant, and Er:YAG lasers for dermatology and dentistry.'],
  [69,'Tm','Thulium',168.934,CAT.LA,16,9,'Thulium was discovered in 1879 by Per Teodor Cleve. Named after Thule, the ancient name for Scandinavia or a mythical island at the northern edge of the world. It is the least abundant naturally occurring lanthanide.','Used in portable X-ray devices, high-performance lasers, and as a source of radiation in nuclear medical devices. Research applications due to its rarity.'],
  [70,'Yb','Ytterbium',173.045,CAT.LA,17,9,'Ytterbium was discovered in 1878 by Jean Charles Galissard de Marignac. Named after Ytterby, Sweden — the fourth element named after this village. Pure ytterbium wasn\'t produced until 1953.','Used in ytterbium-doped fiber lasers (YDFLs) for cutting and welding metals, atomic clocks (ytterbium lattice clocks are the world\'s most precise), and stress gauges.'],
  [71,'Lu','Lutetium',174.967,CAT.TM,3,6,'Lutetium was independently discovered in 1907 by Georges Urbain, Carl Auer von Welsbach, and Charles James. Named after Lutetia, the Latin name for Paris. It ended a decades-long quest to isolate all rare earths.','Used in PET scan detectors (lutetium silicate scintillators), refining petroleum, and Lu-177 is a promising radiopharmaceutical for targeted cancer therapy.'],
  [72,'Hf','Hafnium',178.49,CAT.TM,4,6,'Hafnium was predicted by Niels Bohr and discovered in 1923 by Dirk Coster and Georg von Hevesy using X-ray spectroscopy in zirconium ore. Named after Hafnia, the Latin name for Copenhagen, where it was discovered.','Used in nuclear reactor control rods (excellent neutron absorber), refractory ceramics, semiconductor chips (hafnium oxide as gate dielectric), and plasma cutting torch tips.'],
  [73,'Ta','Tantalum',180.948,CAT.TM,5,6,'Tantalum was discovered in 1802 by Anders Gustav Ekeberg in minerals from Finland and Sweden. Named after Tantalus of Greek mythology (like niobium/Niobe), due to difficulty dissolving it in acid. For a century it was confused with niobium.','Used in capacitors for electronics (phones, computers — world\'s most important use), surgical implants, chemical processing equipment, cutting tools, and camera lenses.'],
  [74,'W','Tungsten',183.84,CAT.TM,6,6,'Tungsten was discovered in 1783 by brothers Juan and Fausto Elhuyar. Its symbol W comes from "wolfram," its German name. It has the highest melting point of all metals (3422°C) and was used for incandescent light bulb filaments.','Used in light bulb filaments (tungsten wire), cutting tools (tungsten carbide), high-speed steel drills, X-ray targets, counterweights in aerospace, and radiation shielding.'],
  [75,'Re','Rhenium',186.207,CAT.TM,7,6,'Rhenium was discovered in 1925 by Walter Noddack, Ida Tacke, and Otto Berg using X-ray spectroscopy in platinum ore. Named after the Rhine River. It was the last naturally occurring stable element to be discovered.','Used in high-temperature superalloys for jet engines (Rolls-Royce uses significant amounts), platinum-rhenium catalysts for unleaded gasoline production, and thermocouples.'],
  [76,'Os','Osmium',190.23,CAT.TM,8,6,'Osmium was discovered in 1803 by Smithson Tennant in the residue left when crude platinum was dissolved in aqua regia. Named after Greek "osme" for smell, due to the pungent odor of osmium tetroxide.','Used in osmium-iridium alloys for fountain pen tips, electrical contacts, and compass bearings; osmium tetroxide is a biological stain in electron microscopy.'],
  [77,'Ir','Iridium',192.217,CAT.TM,9,6,'Iridium was discovered in 1803 alongside osmium by Smithson Tennant. Named after Iris, the Greek goddess of the rainbow, due to the variety of colors in its salts. A thin global iridium layer marks the K-Pg extinction event.','Used in high-temperature crucibles, spark plugs for aircraft engines, scientific instruments requiring extreme corrosion resistance, and as a mass standard (the kg prototype included iridium).'],
  [78,'Pt','Platinum',195.084,CAT.TM,10,6,'Platinum was used by pre-Columbian South Americans and introduced to Europe by Antonio de Ulloa in 1735. Named from Spanish "platina" (little silver). It was initially considered a nuisance impurity in silver mining.','Used in catalytic converters (most important use), jewelry, laboratory crucibles, pacemaker electrodes, chemotherapy drugs (cisplatin), and as catalyst for hydrogen fuel cells.'],
  [79,'Au','Gold',196.967,CAT.TM,11,6,'Gold has been known and valued since prehistoric times. The oldest known gold artifacts date to ~4600 BCE in Bulgaria. Its symbol Au comes from Latin "aurum." Gold rushes shaped the history of California, Australia, and South Africa.','Used in jewelry, monetary reserves, electronics (corrosion-free contacts), medical devices, space vehicle shielding, dentistry, and nanoparticles in cancer treatment.'],
  [80,'Hg','Mercury',200.59,CAT.TM,12,6,'Mercury has been known since ancient times and was found in Egyptian tombs dating to ~1500 BCE. Named after the planet Mercury (the fastest-moving planet, like liquid mercury\'s mobility). It\'s the only metal liquid at room temperature.','Historically used in thermometers, barometers, and dental amalgam. Today used in fluorescent lighting, industrial chlorine production, and scientific instruments. Use declining due to toxicity.'],
  [81,'Tl','Thallium',204.383,CAT.PT,13,6,'Thallium was discovered in 1861 by William Crookes using spectroscopy and named after the Greek "thallos" (green shoot) for its bright green spectral line. Its extreme toxicity earned it the nickname "the poisoner\'s poison."','Used in infrared optical materials (thallium bromide iodide), heart imaging (Tl-201 isotope for myocardial perfusion scans), and some specialized electronics. Medical use declining.'],
  [82,'Pb','Lead',207.2,CAT.PT,14,6,'Lead has been used since at least 7000 BCE — among the earliest metals smelted. The Romans used it extensively for pipes, cookware, and wine sweetener (leading to speculative links to Roman decline). Its symbol Pb comes from Latin "plumbum."','Used in lead-acid batteries (cars), radiation shielding, ammunition, cable sheathing, and historically in paint and plumbing (now largely banned due to neurotoxicity).'],
  [83,'Bi','Bismuth',208.980,CAT.PT,15,6,'Bismuth was recognized as a distinct element in 1753 by Claude François Geoffroy. Named from German "Wismut" (white mass). It was often confused with lead and tin historically. It\'s the most naturally diamagnetic element.','Used in medications (Pepto-Bismol for indigestion), cosmetics (bismuth oxychloride in makeup), lead-free solders and alloys, fire-detection systems, and nuclear medicine.'],
  [84,'Po','Polonium',209,CAT.NM,16,6,'Polonium was discovered in 1898 by Marie and Pierre Curie while studying radioactive materials from pitchblende ore. Named after Marie Curie\'s native Poland. It was the first element discovered by the Curies.','Used in antistatic devices (polonium-210 ionizes air), anti-static brushes for film and optics, and as a heat source in space probes and nuclear weapons triggers.'],
  [85,'At','Astatine',210,CAT.HA,17,6,'Astatine was first synthesized in 1940 by Dale Corson, Kenneth MacKenzie, and Emilio Segrè at UC Berkeley by bombarding bismuth with alpha particles. Named from Greek "astatos" meaning unstable. It is the rarest naturally occurring element.','Investigated for targeted cancer radiotherapy (At-211 is ideal for killing cancer cells with minimal surrounding tissue damage), but applications are limited by its extreme rarity.'],
  [86,'Rn','Radon',222,CAT.NG,18,6,'Radon was discovered in 1899 by Ernest Rutherford and Robert Bowie Owens. Friedrich Ernst Dorn identified it as a noble gas in 1900. Named from radium. It\'s the heaviest noble gas and a significant natural radiation source.','No commercial uses due to radioactivity. Radon-222 has been used in some cancer radiation therapies historically. It is primarily known as a health hazard in buildings — a leading cause of lung cancer.'],
  [87,'Fr','Francium',223,CAT.AK,1,7,'Francium was discovered in 1939 by Marguerite Perey at the Curie Institute in Paris, making her the first woman to discover an element. Named after France, her homeland. It is the second rarest naturally occurring element.','No practical uses due to extreme radioactivity and rarity. Used only for fundamental scientific research on atomic structure and weak force measurements.'],
  [88,'Ra','Radium',226,CAT.AE,2,7,'Radium was discovered in 1898 by Marie and Pierre Curie in pitchblende ore. Isolating 1 gram required processing 10 tons of ore. Marie Curie won her second Nobel Prize for isolating radium in 1911. Radium watch dials caused tragedies for "Radium Girls."','Historically used in luminous paint ("radium girls" tragedy), cancer treatments, and radon production. Now mostly replaced by safer alternatives, though Ra-223 treats bone metastases.'],
  [89,'Ac','Actinium',227,CAT.AC,4,10,'Actinium was discovered in 1899 by André-Louis Debierne in pitchblende residue from the Curies\' radium work. Named from Greek "aktinos" meaning ray. It is 150 times more radioactive than radium and gives actinide series its name.','Ac-225 is used in targeted alpha therapy for cancer treatment. Historically used as a source of neutrons. Research into Ac-227 as a radioisotope generator for medical applications.'],
  [90,'Th','Thorium',232.038,CAT.AC,5,10,'Thorium was discovered in 1829 by Jöns Jacob Berzelius in a Norwegian mineral. Named after Thor, the Norse god of thunder. Early use in gas mantle lanterns. Thorium is three times more abundant than uranium.','Used in thorium-magnesium alloys for aerospace, tungsten welding electrodes, high-refractive-index optical glass, and as a potential nuclear fuel for safer thorium reactors.'],
  [91,'Pa','Protactinium',231.036,CAT.AC,6,10,'Protactinium was discovered in 1913 by Kasimir Fajans and Oswald Helmuth Göhring, and more completely characterized in 1917 by Lise Meitner and Otto Hahn. Named from Greek "protos" (first) + actinium, since it decays to actinium.','No significant commercial uses due to rarity and radioactivity. Used in research for uranium-235/protactinium-231 dating of ocean sediments and climate research.'],
  [92,'U','Uranium',238.029,CAT.AC,7,10,'Uranium was discovered in 1789 by Martin Heinrich Klaproth in the mineral uraninite (pitchblende). Named after the recently discovered planet Uranus. Its radioactivity was discovered by Henri Becquerel in 1896.','Used as fuel in nuclear power reactors (provides ~10% of world electricity), in nuclear weapons, as ballast in aircraft (depleted uranium), and historically as yellow glass colorant.'],
  [93,'Np','Neptunium',237,CAT.AC,8,10,'Neptunium was the first transuranic element, synthesized in 1940 by Edwin McMillan and Philip Abelson at Berkeley by bombarding uranium with neutrons. Named after Neptune, the next planet after Uranus (following uranium\'s naming pattern).','Np-237 is used in neutron detectors, and as a precursor in the production of Pu-238 for nuclear batteries used in spacecraft (such as Voyager and Cassini).'],
  [94,'Pu','Plutonium',244,CAT.AC,9,10,'Plutonium was synthesized in 1940 by Glenn Seaborg, Edwin McMillan, Joseph Kennedy, and Arthur Wahl at Berkeley. Named after Pluto. Plutonium-239 became critical for the Manhattan Project and the Trinity test.','Used as fuel in nuclear reactors and weapons, and Pu-238 powers the radioisotope thermoelectric generators (RTGs) of deep space probes including Voyager, Cassini, and New Horizons.'],
  [95,'Am','Americium',243,CAT.AC,10,10,'Americium was first synthesized in 1944 by Glenn Seaborg, Ralph James, Leon Morgan, and Albert Ghiorso at Chicago. Named after the Americas. It was produced secretly during WWII as part of the Manhattan Project.','Am-241 is found in virtually every household smoke detector — its alpha radiation ionizes air to detect smoke particles. Also used in thickness gauges and medical diagnostic sources.'],
  [96,'Cm','Curium',247,CAT.AC,11,10,'Curium was synthesized in 1944 by Glenn Seaborg, Ralph James, and Albert Ghiorso at the University of Chicago. Named after Marie and Pierre Curie. Seaborg joked it should have been called "cyclonium" since it was made in a cyclotron.','Used as a power source in RTGs for spacecraft (Cm-242, Cm-244), alpha-particle X-ray spectrometers on Mars rovers (Spirit, Opportunity), and as a neutron source.'],
  [97,'Bk','Berkelium',247,CAT.AC,12,10,'Berkelium was first synthesized in 1949 by Glenn Seaborg, Stanley Thompson, and Albert Ghiorso at UC Berkeley by bombarding americium with alpha particles. Named after Berkeley, California.','No current practical applications due to extreme rarity and high radioactivity. Used only in basic nuclear research and as a target material to synthesize heavier elements.'],
  [98,'Cf','Californium',251,CAT.AC,13,10,'Californium was first synthesized in 1950 by Glenn Seaborg, Stanley Thompson, Kenneth Street Jr., and Albert Ghiorso at UC Berkeley. Named after California and UC Berkeley.','Used as a neutron source for nuclear reactor startup and well logging in oil and gas industry, neutron activation analysis to identify materials, and treating certain cancers.'],
  [99,'Es','Einsteinium',252,CAT.AC,14,10,'Einsteinium was discovered in the fallout from the first hydrogen bomb test (Ivy Mike, 1952). Named after Albert Einstein. Its discovery was classified for several years. It was the seventh transuranic element identified.','No practical uses due to extreme rarity (only nanograms ever produced). Used only in research to study the properties of heavy actinides and to synthesize heavier elements.'],
  [100,'Fm','Fermium',257,CAT.AC,15,10,'Fermium was also discovered in the Ivy Mike hydrogen bomb fallout in 1952 and named after Enrico Fermi, the architect of the first nuclear reactor. Like einsteinium, its discovery was initially classified.','No practical applications due to extreme rarity and radioactivity. Used only in fundamental nuclear physics research. Cannot be produced in weighable quantities.'],
  [101,'Md','Mendelevium',258,CAT.AC,16,10,'Mendelevium was first synthesized in 1955 by Glenn Seaborg, Bernard Harvey, Gregory Choppin, Stanley Thompson, and Albert Ghiorso. Named after Dmitri Mendeleev, who created the periodic table.','No practical uses; only a few atoms have ever been produced. Studied to understand the chemical properties of heavy actinides and to test nuclear models.'],
  [102,'No','Nobelium',259,CAT.AC,17,10,'Nobelium was first unambiguously synthesized in 1966 at the Joint Institute for Nuclear Research in Dubna, Russia. Named after Alfred Nobel, founder of the Nobel Prizes. Earlier claimed discoveries were disputed.','No practical applications; only tiny amounts have been produced. Exists only for fractions of a second to minutes. Used in nuclear structure research.'],
  [103,'Lr','Lawrencium',266,CAT.AC,18,10,'Lawrencium was first synthesized in 1961 by Albert Ghiorso and colleagues at Berkeley. Named after Ernest Lawrence, inventor of the cyclotron. It is the last actinide and heaviest element in the f-block.','No practical applications. Used only in nuclear physics research to study the properties of transactinide elements and test theoretical models of heavy atom chemistry.'],
  [104,'Rf','Rutherfordium',267,CAT.TM,4,7,'Rutherfordium was first synthesized in 1969 at the Joint Institute for Nuclear Research in Dubna and UC Berkeley. Named after Ernest Rutherford. There was a naming dispute between American ("unnilquadium") and Soviet teams for decades.','No applications. Only a few atoms have ever been created, lasting seconds to minutes. Studied to test if superheavy elements follow expected periodic trends.'],
  [105,'Db','Dubnium',268,CAT.TM,5,7,'Dubnium was synthesized independently at Dubna (Russia) and Berkeley (USA) in 1967–1970. Named after Dubna, Russia, after a long naming dispute. The American name "hahnium" was used for a period before IUPAC decided.','No applications. Less than a million atoms have ever been made. Only useful for nuclear physics research to probe the limits of the periodic table and nuclear stability.'],
  [106,'Sg','Seaborgium',269,CAT.TM,6,7,'Seaborgium was first synthesized in 1974 at Lawrence Berkeley National Laboratory. Named after Glenn Seaborg — the only element named after a living person at the time of naming (controversial). Seaborg joked he could mail letters "from his element."','No practical applications. Only a few hundred atoms have ever been created. Used in research on superheavy element chemistry and nuclear physics.'],
  [107,'Bh','Bohrium',270,CAT.TM,7,7,'Bohrium was first synthesized in 1981 by a team led by Peter Armbruster and Gottfried Münzenberg at GSI Darmstadt, Germany. Named after Niels Bohr, the Danish physicist who developed the atomic model.','No practical applications. Only a few dozen atoms have ever been made, each lasting less than a second to tens of seconds. Used only in nuclear physics research.'],
  [108,'Hs','Hassium',277,CAT.TM,8,7,'Hassium was first synthesized in 1984 by a German team at GSI Darmstadt. Named after Hassia, the Latin name for the German state of Hesse where GSI is located. Only a few atoms have been created.','No practical applications. A 2006 experiment showed hassium behaves like osmium in chemical reactions, confirming periodic table predictions for superheavy elements.'],
  [109,'Mt','Meitnerium',278,CAT.UK,9,7,'Meitnerium was first synthesized in 1982 at GSI Darmstadt. Named after Lise Meitner, the Austrian physicist who co-discovered nuclear fission and was unjustly passed over for the Nobel Prize. One of very few elements named after a woman.','No practical applications. Only a few atoms have been made. Named as a tribute to Meitner\'s contributions to nuclear physics, which were underrecognized during her lifetime.'],
  [110,'Ds','Darmstadtium',281,CAT.UK,10,7,'Darmstadtium was first synthesized in 1994 at GSI Darmstadt, Germany. Named after the city of Darmstadt. It took the team about a week of experiments to produce just one atom. Previously called "ununnilium."','No practical applications. Only a handful of atoms have ever been created, each decaying within microseconds to seconds. Used only in nuclear physics research.'],
  [111,'Rg','Roentgenium',282,CAT.UK,11,7,'Roentgenium was first synthesized in 1994 at GSI Darmstadt. Named after Wilhelm Röntgen, discoverer of X-rays. Previously known as "unununium." Only a few atoms have been created.','No practical applications. Atoms last microseconds to seconds. The naming honors Röntgen\'s revolutionary discovery of X-rays in 1895, which transformed medicine.'],
  [112,'Cn','Copernicium',285,CAT.TM,12,7,'Copernicium was first synthesized in 1996 at GSI Darmstadt. Named after astronomer Nicolaus Copernicus, who proposed the heliocentric model. Confirmed and officially named in 2010 — on the 537th anniversary of Copernicus\'s birth.','No practical applications. Theoretical predictions suggest it might behave as a noble gas rather than a metal at room temperature, making it chemically unique among group 12 elements.'],
  [113,'Nh','Nihonium',286,CAT.PT,13,7,'Nihonium was first synthesized in 2004 at RIKEN in Japan. Named after Nihon, the Japanese word for Japan — making it the first element discovered in Asia. Official recognition came in 2016 after years of verification.','No practical applications. It took 9 years and 400 trillion fusion attempts to produce just three atoms. Named to honor Japan\'s scientific achievement.'],
  [114,'Fl','Flerovium',289,CAT.PT,14,7,'Flerovium was first synthesized in 1999 at the Joint Institute for Nuclear Research in Dubna. Named after Flerov Laboratory (named after physicist Georgy Flyorov, who also wrote a famous letter urging the Soviet atomic bomb program).','No practical applications. Theoretically sits at the "island of stability" — a predicted region where superheavy nuclei might be unusually long-lived. Research is ongoing.'],
  [115,'Mc','Moscovium',290,CAT.PT,15,7,'Moscovium was first synthesized in 2003 jointly by Dubna (Russia) and Livermore (USA). Named after Moscow Oblast, where Dubna is located. Officially named in 2016. Previously called "ununpentium."','No practical applications. Part of the "island of stability" research zone. A handful of atoms produced, each lasting microseconds. Nuclear physics research only.'],
  [116,'Lv','Livermorium',293,CAT.PT,16,7,'Livermorium was first synthesized in 2000 at Dubna in collaboration with Lawrence Livermore National Laboratory, after whom it\'s named. Previously called "ununhexium." Officially named in 2012.','No practical applications. Expected to behave chemically like polonium. Research into its properties may confirm or challenge periodic table predictions for superheavy elements.'],
  [117,'Ts','Tennessine',294,CAT.HA,17,7,'Tennessine was first synthesized in 2010 at Dubna with contributions from Oak Ridge, Vanderbilt University, and Vanderbilt University Medical Center — all in Tennessee. Named after Tennessee. One of the heaviest known elements.','No practical applications. Part of ongoing research into the island of stability. Only a few atoms have been created, each decaying in milliseconds.'],
  [118,'Og','Oganesson',294,CAT.NG,18,7,'Oganesson was first synthesized in 2002 at Dubna. Named after physicist Yuri Oganessian, a pioneering superheavy element researcher — only the second element named after a living person. Previously called "ununoctium." Officially named 2016.','No practical applications. Theoretically the heaviest element in the noble gas group, but predicted to be solid at room temperature and highly reactive — defying noble gas trends. Pure research only.'],
];

// Build element position map
const cells = Array(18 * 10).fill(null);
elements.forEach(e => {
  const [num, sym, name, mass, cat, col, row] = e;
  const idx = (row - 1) * 18 + (col - 1);
  cells[idx] = e;
});

const lantLabel = { idx: (8 - 1) * 18 + (3 - 1), text: '57-71' };
const actLabel  = { idx: (9 - 1) * 18 + (3 - 1), text: '89-103' };

const grid = document.getElementById('ptable');
let activeEl = null;

function buildTable() {
  for (let i = 0; i < 18 * 10; i++) {
    const el = document.createElement('div');

    if (i === lantLabel.idx) {
      el.className = 'series-label';
      el.textContent = lantLabel.text;
      grid.appendChild(el);
      continue;
    }
    if (i === actLabel.idx) {
      el.className = 'series-label';
      el.textContent = actLabel.text;
      grid.appendChild(el);
      continue;
    }

    const data = cells[i];
    if (!data) {
      el.style.background = 'transparent';
      el.style.border = 'none';
      grid.appendChild(el);
      continue;
    }

    const [num, sym, name, mass, cat] = data;
    el.className = `el cat-${cat}`;
    el.innerHTML = `
      <span class="num">${num}</span>
      <span class="sym">${sym}</span>
      <span class="name">${name}</span>
    `;
    el.title = name;
    el.onclick = () => showElement(data);
    grid.appendChild(el);
  }
}

function showElement(data) {
  const [num, sym, name, mass, cat, col, row, history, uses] = data;

  document.getElementById('bNum').textContent = num;
  document.getElementById('bSym').textContent = sym;
  document.getElementById('bName').textContent = name;
  document.getElementById('bMass').textContent = mass;

  const color = catColors[cat];
  const badge = document.getElementById('infoBadge');
  badge.querySelector('.b-sym').style.color = color;

  const catName = {
    alkali: 'Alkali Metal', alkaline: 'Alkaline Earth Metal',
    lanthanide: 'Lanthanide', actinide: 'Actinide',
    transition: 'Transition Metal', 'post-transition': 'Post-Transition Metal',
    metalloid: 'Metalloid', nonmetal: 'Nonmetal',
    halogen: 'Halogen', noble: 'Noble Gas', unknown: 'Unknown'
  }[cat];

  document.getElementById('infoMeta').innerHTML = `
    <span>Category: <strong>${catName}</strong></span>
    <span>Atomic Mass: <strong>${mass}</strong></span>
    <span>Period: <strong>${row}</strong></span>
    <span>Group: <strong>${col}</strong></span>
  `;

  document.getElementById('infoHistory').textContent = history;
  document.getElementById('infoUses').textContent = uses;

  // Apply category accent color to modal border
  const modal = document.getElementById('infoPanel');
  modal.style.borderColor = color + '55';
  modal.style.boxShadow = `0 32px 90px rgba(0,0,0,0.75), 0 0 0 1px ${color}20`;

  if (activeEl) activeEl.classList.remove('active');
  document.querySelectorAll('.el').forEach(e => {
    if (e.querySelector('.sym') && e.querySelector('.sym').textContent === sym) {
      e.classList.add('active');
      activeEl = e;
    }
  });

  document.getElementById('modalOverlay').classList.add('visible');
  document.getElementById('infoPanel').classList.add('visible');
}

function closePanel() {
  document.getElementById('infoPanel').classList.remove('visible');
  document.getElementById('modalOverlay').classList.remove('visible');
  if (activeEl) activeEl.classList.remove('active');
  activeEl = null;
}

buildTable();
document.addEventListener('keydown', e => { if (e.key === 'Escape') closePanel(); });